#对内置tomcat的配置
server:
  # 配置服务器的http端口号
  port: 9088
  servlet:
    context-path:



#配置数据源及数据连接
spring:
  datasource:
    #mysql驱动，适用于5.X版本。8.X版本配置是  driver-class-name:com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url的配置，///代表本机，也就是localhost 这里的bookstore是数据库的名字
    url: jdbc:mysql://localhost:3306/hw?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123123


#分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql




